apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: sampleoutput
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/bhargavim613/tekton.git
    - name: revision
      value: master